### ISSUE TITLE
This looks handy!

### ISSUE THREAD

**Issue by mcclowes** [dronsfield/playlists#1]
What are you migrating to?

**Comment by dronsfield** [comment]
staying with spotify - just felt my playlists are too valuable to me and too easy to accidentally delete to not have any backup

didn't want to use a third party export service because they require permissions to CRUD your playlists so I'm paranoid about something going wrong and things getting deleted

**Comment by mcclowes** [comment]
Niiice, it's a great idea, will do it myself!
